global using Microsoft.AspNetCore.Http;
global using Microsoft.EntityFrameworkCore;
global using Solution.Common.Enums;
global using Solution.Core.Interfaces;
global using Solution.Database;
global using Solution.Database.Entities;
global using Solution.Services;
global using Solution.Core.Models.Request;
global using Solution.Core.Models.Response;